---
- name: Install and Configure Docker and Docker Compose
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and Enable Docker Service
      service: 
        name: docker
        state: started
        enabled: true

    - name: Add User to Docker Group
      command: usermod -aG docker "{{ ansible_user }}"

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Check Docker Compose Version
      command: docker-compose --version
      register: compose_version
      changed_when: false

    - name: Show Docker Compose Version
      debug:
        msg: "{{ compose_version.stdout }}"
